### ISSUE TITLE
Copy to clipboard button turns gray when pressed

### ISSUE THREAD

**Issue by PascalPrecht** [status-im/nim-status-client#1599]
The `CopyToClipBoardButton` comes with a default "pressed" effect which turns the button dark gray.
We need to remove this. There's probably another component used under the hood where it comes from.
Expected behaviour is basically not having a pressed state at all.

**Comment by staked-smart-ace** [comment]
This issue is fixed by #1455 
But I found a side-effect from that fix, it is showing an empty tooltip in other views (ex: profile view)
I think the toolip shouldn't be show when the tooltip text param is null or empty string or show default string to be copied.
What is your opinions for this issue?
If you create a new ticket for this issue, let me try to fix it.

**Comment by PascalPrecht** [comment]
> What is your opinions for this issue?
You're correct, I left a comment here:
https://github.com/status-im/nim-status-client/pull/1644#issuecomment-759316026

> This issue is fixed by #1455
That's right. The PR seems to address this. Thank you! Closing this one.
