### ISSUE TITLE
store data folder in appropriate OS recommended location

### ISSUE THREAD

**Issue by iurimatias** [status-im/nim-status-client#391]
Currently the `data/` folder is being stored relative to the binary, this isn't ideal and will in fact nuke the database if the user attempts to update the app. we should instead load & store the `data/` and other relevant files from the OS appropriate folders

**Comment by michaelsbradleyjr** [comment]
Windows: `%HOME%\AppData\Local\Status\`
macOS: `${HOME}/Library/Application Support/Status/`
Linux: `${HOME}/.config/status/`

Based on https://whatsabyte.com/mac/find-chrome-profile-folders-windows-mac-linux/

**Comment by zah** [comment]
Mane applications tend to use separate data folders for the roaming user profile and caching databases.

The roaming profile includes configuration and other data that was "entered by the user". It is the minimal amount of files that you need to synchronize between two computers to recreate the same user experience. It's usually small.

The caching database is something that can recreated from the information in the roaming profile. It can include significantly more data such as chat histories, downloaded media files, web3 browsing caches, etc. 

The usual suggested directories for the two data folders:

Windows:

Roaming profile: %HOME%\AppData\Roaming\Status\
Cache directory: %HOME%\AppData\Local\Status\

Linux: 

Roaming profile: `$XDG_CONFIG_HOME/status` (by default `${HOME}/.config/status/`)
Cache directory: `$XDG_CACHE_HOME/status`  (by default `${HOME}/.cache/status/`)

macOS:

Roaming profile: `${HOME}/Library/Preferences/Status`
Cache directory: `${HOME}/Library/Application Support/Status`

**Comment by michaelsbradleyjr** [comment]
Thanks @zah! I didn't see your reply until a couple of minutes ago.

Currently, the client creates two directories `DATADIR` and `KEYSTOREDIR`. Actually, it's status-go within the client that writes data to those directories. It's not entirely clear if/how we should apply Roaming vs. Cache (per your comment above) to those directories. Thoughts?

**Comment by zah** [comment]
Without being fully certain, I expect that the `DATADIR` in Status Go stores the downloaded blockchain data, which is not personal and can be downloaded from public sources on any machine, so it can safely be treated as a cache directory.

The Keystores are personal data, but it's a matter of UX design to decide whether the password for unlocking then should be device-specific. If the passwords are device-specific, they keystores should also go in the "local data" dir, otherwise they can be considered a part of the roaming profile.
