### ISSUE TITLE
expose QT Concurrency API

### ISSUE THREAD

**Issue by iurimatias** [status-im/nim-status-client#517]
expose this in nimqml / dotherside so we can take advantage of it in the app

**Comment by zah** [comment]
You need to be careful in Nim when working with threads that were created outside of the Nim run-time. Each such thread should call `setupForeignThreadGc` before entering the Nim code. For more details, please see here:

https://nim-lang.github.io/Nim/backends.html#memory-management-thread-coordination

The thread-local heaps of Nim are another thing you need to keep in mind. Don't store references to Nim ref objects in Qt structures unless you can guarantee that the Nim objects will always be accessed from the same thread (but be aware that this applies only for the garbage collected ref types). 

If you run into any "gc safety" issues caused by global variables, don't be lured to silence the compiler with `{.gcsafe.}: block` overrides. This is asking for troubles and it's safe only when the above "same thread" guarantee holds.
