### ISSUE TITLE
A race condition in status-go?

### ISSUE THREAD

**Issue by michaelsbradleyjr** [status-im/nim-status-client#522]
While working on #521, when running `nim_status_client.exe` I encounter frequent crashes related to status-go:

```
goroutine 397 [running]:
github.com/status-im/status-go/peers.(*TopicPool).processFoundNode(0xc0002481e0, 0xc00014edc0, 0xc002397340, 0x0, 0x0)
        C:/Users/michael/repos/nim-status-client/vendor/status-go/peers/topicpool.go:504 +0x63f
github.com/status-im/status-go/peers.(*TopicPool).handleFoundPeers(0xc0002481e0, 0xc00014edc0, 0xc000300de0, 0xc00026e1c0)
        C:/Users/michael/repos/nim-status-client/vendor/status-go/peers/topicpool.go:459 +0x229
github.com/status-im/status-go/peers.(*TopicPool).StartSearch.func2(0xc0002481e0, 0xc00014edc0, 0xc000300de0, 0xc00026e1c0)
        C:/Users/michael/repos/nim-status-client/vendor/status-go/peers/topicpool.go:441 +0x50
created by github.com/status-im/status-go/peers.(*TopicPool).StartSearch
        C:/Users/michael/repos/nim-status-client/vendor/status-go/peers/topicpool.go:440 +0x39f
QObject::~QObject: Timers cannot be stopped from another thread
QWaitCondition: Destroyed while threads are still waiting
```

It doesn't happen every time I run `nim_status_client.exe`, but it does happen most of the time, usually soon after starting the app. For reasons unknown at present, the crash has never been encountered (as far as I know) with the Linux and macOS builds.

There was some discussion about this problem yesterday in `#desktop` on discord (cc: @cammellos).

**Comment by michaelsbradleyjr** [comment]
Still a problem as of merging #589.

**Comment by cammellos** [comment]
@michaelsbradleyjr would you mind enabling debug logs and giving me the `geth.log` if you manage to replicate? 
Thanks!

**Comment by cammellos** [comment]
Also, which version of golang are you using? (it should be 1.14, as I am not sure we support 1.13)

**Comment by michaelsbradleyjr** [comment]
> Also, which version of golang are you using? (it should be 1.14, as I am not sure we support 1.13)

I'm building on Windows with `go version go1.14.3 windows/amd64`

**Comment by michaelsbradleyjr** [comment]
> would you mind enabling debug logs

Is that something I do as part of the step for compiling status-go into `libstatus.a`, or what do you mean exactly?

**Comment by cammellos** [comment]
no,  when you pass a config to `status-go` on starting the node, here https://github.com/status-im/nim-status-client/blob/15a860b2bb742b51c62c9065e3cc3d3b0c968350/src/status/libstatus/accounts/constants.nim#L135 
if you could set that one to `DEBUG`, replicate it and send me the `geth.log` would be very helpful, thanks!

**Comment by michaelsbradleyjr** [comment]
@cammellos with debug logs enabled it took a lot more tries to trigger the problem, but it still happened eventually:

https://gist.github.com/michaelsbradleyjr/5337a91f4f6c66681e8ee3f2819cf21a

And here's the corresponding console output:

https://gist.github.com/michaelsbradleyjr/d7d2b900a016c94701ebe46ed4bf6b43

**Comment by cammellos** [comment]
@michaelsbradleyjr thanks, very helpful.

I have narrowed down the possibilities to two options:
1) Locks are not properly working, allowing concurrent access to those data structures (highly unlikely)

2) The peer just added is removed in the same call as it is found to be the oldest peer. https://github.com/status-im/status-go/blob/0b3cdf7362bbdf9ba7fc11da803105f9417dfbac/peers/topicpool.go#L120 

2 might happen because for a few reasons, but essentially if `discoveredTime` is the same for the new peer and the ones in already present, it might be that the peer just added is the one that is removed. 

The clock is using is a monotonic clock and is linked at runtime (https://github.com/aristanetworks/goarista/blob/master/monotime/nanotime.go) , it should be in nanoseconds, so one guess is that either the clock on windows is not precise enough, effectively resulting in multiple peers having the same discovery time, or you are running this on a quantum computer, and multiple adding to the map  happen in the same nanosecond.

To get a bit more understanding, I have added some logs to a branch,  https://github.com/status-im/status-go/tree/debug/peer-pool , it would be handy if you could replicate with debug logs as you did before using this branch.
I guess you will need to update `nim-status` as well so that it's using this version, @richard-ramos can probably assist with that if needed.
The fix in any case should be pretty straightforward if it's issue 2.
I would try to replicate myself but I haven't a window machine, but if you don't have time I can set up one.

Thank you!

**Comment by michaelsbradleyjr** [comment]
@cammellos here are the logs when using your `debug/peer-pool` branch for status-go:

https://gist.github.com/michaelsbradleyjr/015d6df8c28186e85b8413511f964120

And here's the corresponding console output:

https://gist.github.com/michaelsbradleyjr/d43bf7a1e423d1bc75327ca344c3fc5c

Sorry for the delay, it took an even larger number of runs before the crash was triggered.
