### ISSUE TITLE
modal to authorize sticker transaction

### ISSUE THREAD

**Issue by iurimatias** [status-im/nim-status-client#556]

**Comment by emizzle** [comment]
Instead of one task for the sticker market transaction modal, @PascalPrecht and I have discussed, and we decided we will handle wallet, sticker market, and command transactions with reusable components, as outlined in https://www.notion.so/emizzle/Wallet-transaction-components-2003b78a8d0d41c4ab3d21eb2496fb20. 

I will create tasks for each of the components.
