### ISSUE TITLE
add contact (in profile section) doesn't work when opened for the first time

### ISSUE THREAD

**Issue by iurimatias** [status-im/nim-status-client#839]
1. go to profile -> contacts
2. click add new contact
3. input a pubkey

result: add button is still disabled
however closing the modal and reopening it will work

**Comment by PascalPrecht** [comment]
This one is due to what's expected and what's not.. Based on the designs, it looked like the `add button` should stay disabled **until** a contact with the given pubkey was found (`input pubkey` -> `hit enter` -> `if user found, enable button`)

Here are the two states as of screen designs:
<img width="745" alt="Screenshot 2020-09-08 at 09 41 13" src="https://user-images.githubusercontent.com/445106/92447389-7310a000-f1b7-11ea-865e-9edd659cbf11.png">
<img width="748" alt="Screenshot 2020-09-08 at 09 41 37" src="https://user-images.githubusercontent.com/445106/92447445-80c62580-f1b7-11ea-8d13-3dc5bcfea84e.png">

Notice how the `add contact` button is enabled after a pubkey was entered and a matching user was found.

**^ If that's the desired behaviour, then it works as expected in the app**

**Comment by hesterbruikman** [comment]
@PascalPrecht right, can't imagine the desired behavior being different. I wonder what the issue is here. Sounds like public chat key was not recognized as a chat key.

If recognized as chat key, the key should be shown without name (in case of no ENS name)

**Comment by simonricoo** [comment]
@PascalPrecht The behaviour of adding a contact is right as you explained it :)
